[package]
name = "matrix-tabs"
version = "0.1.0"
authors = ["Victor Berger <victor.berger@m4x.org>"]

[dependencies]
glitch-in-the-matrix = "0.11.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rpassword = "1.0"
tokio-core = "0.1"
futures = "0.1.14"
clap="~2.27.1"
